#!/bin/sh

# This script runs all ncunit tests inside ./test/

DATE="$(date +%Y-%m-%d-%T)";
echo "Writing results to $DATE-test\n"

for file in test/*; do
	echo "$file" | tee $DATE-test -a;
	./$file 2>&1 | tee $DATE-test -a;
done;

ERRORS=$(cat $DATE-test | grep "\[nunit\] XX" | wc - -l | cut -f 1 -d ' ');
# rm $DATE-test 	uncomment this line if too many test logs annoys you
if [ $ERRORS -eq 0 ]; then
	exit 0;
else
	echo "$ERRORS ERRORS"
	exit 1;
fi
